# Generated by Django 2.0.13 on 2019-08-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='mobile_no',
            new_name='mobile_number',
        ),
    ]
