# Generated by Django 2.0.13 on 2019-08-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0002_auto_20190809_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='work',
            field=models.TextField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
